services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    image: "${DOCKERHUB_USERNAME}/my-shop-frontend:${IMAGE_TAG}"
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_URL
    ports:
      - "3000:80"
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    pid: "host"
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
